apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: codecomrade/otus-kuber:microservices-demo-paymentservice-v2
        imagePullPolicy: Always
        name: server
        resources: {}
